services:

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - bot/config/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    user: "0:0"
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"  # Изменили порт на 5050
    env_file:
      - bot/config/.env
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  bot:
    restart: unless-stopped
    build: ./
    env_file:
      - bot/config/.env
    volumes:
      - ./logs:/app/bot/logs
    depends_on:
      - postgres

